# 数据相关配置
data:
  file_path: "data/raw/online_retail_09_10.csv"
  
# 特征工程配置
features:
  min_days: 30
  windows: [7, 14, 30]

# 生命周期标签配置
lifecycle:
  method: "simple"  # 可选: "simple", "rule_based", "percentile", "model_based"
  thresholds:
    intro_growth: 0
    intro_rel_sales: 0.25
    growth_rel_sales: [0.25, 0.7]
    growth_trend: 0.05
    mature_rel_sales: 0.7
    mature_trend: 0.05
    decline_trend: -0.05

# 模型配置
model:
  type: "hybrid"  # 可选: "lstm", "hybrid"
  sequence_length: 30
  batch_size: 32
  epochs: 50
  patience: 10
  test_size: 0.2
  validation_split: 0.2

# 可视化配置
visualization:
  n_samples: 5
  output_dir: "./results"
  dpi: 300